//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_web_quản_lí_phòng_trọ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuTien
    {
        public int MaPhieuThuTien { get; set; }
        public int TongTien { get; set; }
        public int Thang { get; set; }
        public int TienDien { get; set; }
        public int TienNuoc { get; set; }
        public int TienMang { get; set; }
        public string TrangThai { get; set; }
        public int MaQuanLy { get; set; }
        public int MaKhachHang { get; set; }
        public int MaPhieuTTP { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhieuThueTraPhong PhieuThueTraPhong { get; set; }
        public virtual QuanLy QuanLy { get; set; }
    }
}
