//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_web_quản_lí_phòng_trọ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThueTraPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuThueTraPhong()
        {
            this.PhieuThuTiens = new HashSet<PhieuThuTien>();
        }
    
        public int MaPhieuTTP { get; set; }
        public string CCCD { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public int MaQuanLy { get; set; }
        public int MaPhong { get; set; }
    
        public virtual PhongTro PhongTro { get; set; }
        public virtual QuanLy QuanLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThuTien> PhieuThuTiens { get; set; }
    }
}
