//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_web_quản_lí_phòng_trọ.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Web;

	public partial class PhongTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongTro()
        {
            this.PhieuThueTraPhongs = new HashSet<PhieuThueTraPhong>();
        }
    
        public int MaPhong { get; set; }
        public int GiaThue { get; set; }
        public int DienTich { get; set; }
        public string VatChat { get; set; }
        public string TrangThai { get; set; }
        public string Hinh { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThueTraPhong> PhieuThueTraPhongs { get; set; }
    }
}
