//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_web_quản_lí_phòng_trọ.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class TaiKhoan
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public TaiKhoan()
		{
            this.KhachHangs = new HashSet<KhachHang>();
        }

		[Required(ErrorMessage = "Mã đăng ký là bắt buộc...")]
		[Display(Name = "Mã đăng kí")]
		public int MaTaiKhoan { get; set; }

		[Required(ErrorMessage = "Tên không được để trống...")]
		[Display(Name = "Tên đăng nhập")]
		public string UserName { get; set; }

		[Required(ErrorMessage = "Mật khẩu không được để trống...")]
		[DataType(DataType.Password)]
		[Display(Name = "Mật khẩu:")]
        public string MatKhau { get; set; }

		[NotMapped]
		[Required(ErrorMessage = "Mật khẩu không trùng khớp...")]
		[Compare("MatKhau")]
		[DisplayName("Nhập lại mật khẩu")]
		public string ConfirmPassword { get; set; }

        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
